scrape_configs:
  - job_name: 'self'
    consul_sd_configs:
      - server: 'consul.service.consul:8500'
        services: []
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*,metrics,.*
        action: keep
      - source_labels: [__meta_consul_service]
        target_label: job

